logging:
  config: classpath:log4j2.yaml

spring:
  servlet:
    multipart:
      resolve-lazily: true

springdoc:
  enable-hateoas: false
  show-actuator: true
  packages-to-scan: org.idiologue

binary:
  storage:
    strategy: block
    block.location: /tmp